# Generated by Django 4.2.6 on 2023-10-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crud_Aman',
            new_name='Crud_Model',
        ),
    ]
